data:
  raw_data_path: "data/raw/chicago_taxi_trips.csv"
  processed_data_path: "data/processed/"

analysis:
  sample_size: 1000000
  random_seed: 42

visualization:
  map_style: "carto-positron"
  default_height: 600
  default_width: 800
