# ML Pipeline Configuration

# Data Processing Parameters
data_processing:
  sample_size: 1000000
  random_seed: 42
  train_test_split: 0.8
  validation_split: 0.1

# Feature Engineering
feature_engineering:
  temporal_features:
    - hour
    - day_of_week
    - month
    - season
  spatial_features:
    - distance
    - pickup_zone
    - dropoff_zone
  weather_features:
    - temperature
    - precipitation
    - wind_speed

forecasting:
  time_column: timestamp_hour
  target_column: trip_count
  time_granularity: "hour"
  context_column: pickup_community_area
  forecast_horizon: 24
  window_size: 168

# Model Parameters
model:
  type: "xgboost"
  params:
    max_depth: 6
    learning_rate: 0.1
    n_estimators: 100
    objective: "reg:squarederror"
    eval_metric: "rmse"

# Training Parameters
training:
  batch_size: 32
  epochs: 100
  early_stopping_rounds: 10
  validation_frequency: 1

# Evaluation Metrics
evaluation:
  metrics:
    - rmse
    - mae
    - r2
  threshold:
    rmse: 5.0
    mae: 4.0
    r2: 0.7

# Deployment Parameters
deployment:
  model_name: "chicago_taxi_demand"
  version: "v1"
  min_instances: 1
  max_instances: 10
  machine_type: "n1-standard-2"

# Monitoring
monitoring:
  prediction_threshold: 1000
  error_rate_threshold: 0.05
  latency_threshold: 200  # ms
  alert_email: "alerts@example.com"

# Resources
resources:
  cpu: 2
  memory: "8Gi"
  gpu: 0
  storage: "100Gi" 